memory_limit = 512M
max_execution_time = 300
date.timezone = UTC

file_uploads = On
upload_max_filesize = 512M
post_max_size = 512M
max_file_uploads = 5

expose_php = Off
allow_url_fopen = Off
allow_url_include = Off
session.cookie_httponly = 1
session.cookie_secure = 0
session.cookie_samesite = "Lax"
session.use_strict_mode = 1

opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 128
opcache.max_accelerated_files = 10000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2

display_errors = Off
log_errors = On
error_log = /proc/self/fd/2

realpath_cache_size = 4096K
realpath_cache_ttl = 600
